define([], function () {
  return {
    PropertyPaneDescription: "Description",
    GeneralGroupName: "General settings",
    SliderGroupName: "Slider settings",
    wpTitleLabel: "Generic Slider Web Part",
    ShowTitleLabel: "Show Title",
    ShowTitleOnText: "On",
    ShowTitleOffText: "Off",
    PageContentTypeFieldLabel: "Page Content Type",
    ShowCarouselLabel: "Show Carousel",
    ShowCarouselOnText: "On",
    ShowCarouselOffText: "Off",
    CarouselGroupName: "Carousel settings",
    ItemsLabel: "Items",
    ItemPerPageLabel: "Items per page",
    ItemToSlideLabel: "Items to slide",
    AutoPlaySpeedLabel: "Auto play speed",
    GridGroupName: "Grid settings",
    gridRowsLabel: "Grid Rows",
    GridOneRow: "Show one row",
    GridTwoRows: "Show two rows",
    GridThreeRows: "Show three rows",
    GridFourRows: "Show four rows",
    GridFiveRows: "Show five rows",
    DisplayOrderLabel: "Display Order",
    OderDirectionLabel: "Order direction",
    AscendingOrder: "Ascending order",
    DescendingOrder: "Descending order",
    FilterFieldLabel: "Filter field",
    FilterValueLabel: "Filter value",
    ItemTitleLabel: "Item Title",
    ItemDescriptionLabel: "Item Description",
    ItemImageUrlLabel: "Item Image URL",
    ItemTagsLabel: "Tags field name",
    ItemTagsTermSetLabel: "Tags Term Set ID",
    ItemDateLabel: "Item Date",
  };
});
